### ISSUE TITLE
Timezone in experimental

### ISSUE THREAD

**Issue by mboehm21** [Screenly/screenly-ose#1038] opened 2019-02-26 12:26 UTC
#### Overview of the Issue

Timezone is incorrect in the Docker-Containers. I think you might need to mount /etc/timezone into the containers to use the same settings as the host.

### Environment

* Raspberry Pi Hardware Version: 3
* Screenly OSE Version: newest experimental

**Comment by vpetersson** [comment] 2019-02-26 23:32
@mboehm21 Timezone should not be configured inside the container - that's a system level functionality that should be inherited into the container. Do you have exact steps to reproduce the issue?

**Comment by mboehm21** [comment] 2019-02-28 08:38
I cannot reproduce it now as I don't have access to the screens. But if I remember correctly pages like http://tagesschau.de/infoscreen showed the wrong time. Can you confirm that?

Also "docker exec -it <container> date" showed the wrong time iirc.

**Comment by vpetersson** [comment] 2019-02-28 09:44
I can't reproduce this:

```
$ date
Thu Feb 28 09:44:17 UTC 2019
$ docker run --rm -ti ubuntu date
Thu Feb 28 09:44:20 UTC 2019
```

**Comment by mboehm21** [comment] 2019-03-01 11:21
Well, try to use something else than UTC outside of the container... UTC is default inside of course.

**Comment by vpetersson** [comment] 2019-03-01 17:38
Interesting. I've used Docker for years but never run into this. Perhaps that is because in the server world, UTC is considered best practice. 

```
$ date
Fri Mar  1 09:32:33 PST 2019

$ docker run --rm -ti ubuntu date
Fri Mar  1 17:32:40 UTC 2019
```

Volume mounting is of course an option, but I've frankly never seen that before. Let me think about this for a bit.

**Comment by vpetersson** [comment] 2019-03-04 22:22
Interesting, I just noticed that in [Home Assistant](https://www.home-assistant.io/docs/installation/docker/), they indeed are volume mounting localtime.

**Comment by reticent98** [comment] 2019-03-07 00:08
This is a very minor issue, but it does fit the discussion. I have been testing meteoTV for displaying weather information: https://www.meteoblue.com/en/meteotv/4c0ef9?

With the 11/23/18 image, the time in the bottom corner displays in my timezone. Under with the new experimental build, the time always displays UTC. I'm going to test some other screen-formatted websites and see if they pull the time the same way.

**Comment by vpetersson** [comment] 2019-03-07 08:14
@reticent98 This is expected as per the above issue.

**Comment by agalewsky** [comment] 2019-03-07 19:33
I can confirm as well with experimental having only UTC is problem.   We have several screens with clocks and it is problematic to say the least.   We are trying to use experimental to see if it fixes the SSL hang problem.

**Comment by PatrickRUG** [comment] 2019-03-12 09:21
I also having issues with this with clocks, our pi is configured at CET, but the docker image is in UTC, therefore DST will not be detected by our clock page.

**Comment by vpetersson** [comment] 2019-03-12 09:56
@rusko124 could you fix this - it's a trivial fix it seems like.

**Comment by bcherup** [comment] 2019-03-21 13:10
Any way for a quick patch ?

**Comment by bcherup** [comment] 2019-03-22 15:44
The fix did not work as Ive already tried this. Heres the command you should run.

pi@raspberrypi:~ $ docker exec -it screenly-ose-viewer date
Fri Mar 22 15:40:21 UTC 2019
pi@raspberrypi:~ $

From what I've read the timezone setting needs passed on the startup line of the container.

**Comment by bcherup** [comment] 2019-03-22 16:41
For the record I rebooted after I updated the file. But I was able to fix the issue with 

git reset --hard
git pull

and restart !

**Comment by vpetersson** [comment] 2019-03-22 17:20
Awesome. Closing out.

**Closed by vpetersson** 2019-03-22 17:20 UTC
