### ISSUE TITLE
last shown image hangs if asset list was cleared

### ISSUE THREAD

**Issue by over64** [Screenly/screenly-ose#463] opened 2016-08-12 11:53 UTC
![image](https://cloud.githubusercontent.com/assets/2621273/17621523/a6a87830-60b5-11e6-9e01-143e33e06bbf.png)

**Comment by IRTermite** [comment] 2016-09-21 02:58
I've also seen it force a reboot on this hang... done it a number of times. Guess that is a watchdog function?

**Comment by vpetersson** [comment] 2016-09-21 08:58
@IRTermite We are using the watchdog device on the Raspberry Pi. The watchdog however is triggered on CPU load (if the load average exceeds certain levels). This may or may not be related to this bug.

**Comment by over64** [comment] 2017-01-09 06:52
@IRTermite, @vpetersson it's scheduler-related

**Comment by vpetersson** [comment] 2017-01-09 10:29
@over64 cool. Alright. It's in this sprint so let's sort it out.

**Comment by antonmolodykh** [comment] 2017-03-29 06:09
@vpetersson the problem is related to the fact that the loading.jpg is missed

**Comment by vpetersson** [comment] 2017-03-29 08:32
@antonmolodykh Interesting. Where is `loading.jpg` used?

Regardless, let's create a pull request and assign it to this Issue.

**Comment by antonmolodykh** [comment] 2017-03-29 09:23
@vpetersson loading.jpg is used in the asset_loop function in viewer.py, in case when the list of asset is empty. I mean that loading desired picture into the project directory is enough to solve the problem (I do not know which picture)

**Comment by vpetersson** [comment] 2017-06-29 11:41
I'm not sure what happened to `loading.jpg`. It used to be the image we displayed when the playlist was empty. I've created a new one (`loading.png`). Let's implement it instead. 

![loading](https://user-images.githubusercontent.com/357664/27685919-40678f38-5cc8-11e7-9dcb-bc32a0e39fe0.png)

**Closed** 2017-06-29 13:18 UTC
Labels: bug, reproducible
