### ISSUE TITLE
Internal Server Error, Clean install of Raspbian Strech lite

### ISSUE THREAD

**Issue by john-arvid** [Screenly/screenly-ose#628] opened 2017-09-08 12:03 UTC
Clean install of Raspbian Strech Lite, clean install of screenly with this command: bash <(curl -sL https://www.screenly.io/install-ose.sh)

No errors in installation. 

Reboots and try to log in on http://raspbianIP:8080

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Tried to look for logs but could now find the screenly_viewer.log anywhere.

\JAK

**Comment by vpetersson** [comment] 2017-09-08 12:41
Duplicate of #624.

**Closed by vpetersson** 2017-09-08 12:41 UTC
