### ISSUE TITLE
Black screen after an indefinite time

### ISSUE THREAD

**Issue by Gifford47** [Screenly/screenly-ose#1262] opened 2019-11-18 12:38 UTC
#### Overview of the Issue
i use a raspi 3b and the official 7" touchscreen display with the latest screenly-ose version. as asset i chose my openhab habpanel. after an indefinite time (i.e. between one and four days) the display remains black and doesn't show any content anymore.
i've been testing everything for two weeks, but haven't found any bugs in my system. sometimes the raspberry stays completely frozen and doesn't even respond to ssh requests anymore.
so far only rasbian has been installed and directly after that screenly.
attached my logs
i also noticed during testing that the "screenly/lib/diagnostics.py" does not work (see log).
urllib3 is installed, so where might the bug be?

#### Reproduction Steps
Steps to reproduce this issue, eg:
* Press Add Asset
* Enter the Asset URL https://local.ip.address
* Press "On"
* Wait for the asset to show up on the screen
*Wait for a black screen

### Environment
* Raspberry Pi Hardware Version: raspberry pi 3b (v1.3)
* official 7" touchscreen display
* 16GB class 10, uhd1, sd card
* 5A power supply
* Screenly OSE Version: 0.18.2

[screenly_journal_log.txt](https://github.com/Screenly/screenly-ose/files/3858617/screenly_journal_log.txt)
[screenly_log.txt](https://github.com/Screenly/screenly-ose/files/3858618/screenly_log.txt)

**Comment by vpetersson** [comment] 2019-11-19 17:36
This sounds like a duplicate of #1222.

**Closed by vpetersson** 2019-11-19 17:36 UTC
