### ISSUE TITLE
Install fails - Pi Zero W - Buster & Bullseye

### ISSUE THREAD

**Issue by AnchorHRG** [Screenly/screenly-ose#1654] opened 2022-11-05 19:06 UTC
When using the install script the install fails on both Buster & Bullseye on Raspberry Pi Zero Ws, unsure about other Pi models.
Install fails on Buster due to Python not being version 3.8, Ansible fails to install.
Here is the log for the Bullseye failed installation:
<details>
<summary>Log</summary>

 ```
      _____                           __         ____  _____ ______
      / ___/_____________  ___  ____  / /_  __   / __ \/ ___// ____/
      \__ \/ ___/ ___/ _ \/ _ \/ __ \/ / / / /  / / / /\__ \/ __/
     ___/ / /__/ /  /  __/  __/ / / / / /_/ /  / /_/ /___/ / /___
    /____/\___/_/   \___/\___/_/ /_/_/\__, /   \____//____/_____/
                                     /____/
Screenly OSE requires a dedicated Raspberry Pi / SD card.
You will not be able to use the regular desktop environment once installed.

Do you still want to continue? (y/N)
Do you want Screenly OSE to manage your network? This is recommended for most users because this adds features to manage your network. (Y/n)

Would you like to perform a full system upgrade as well? (y/N)
+ REPOSITORY=https://github.com/screenly/screenly-ose.git
+ sudo mkdir -p /etc/ansible
+ sudo tee /etc/ansible/hosts
+ echo -e '[local]\nlocalhost ansible_connection=local'
+ '[' '!' -f /etc/locale.gen ']'
+ sudo sed -i s/apt.screenlyapp.com/archive.raspbian.org/g /etc/apt/sources.list
+ sudo apt update -y
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
33 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ sudo apt-get install -y --no-install-recommends git libffi-dev libssl-dev python3 python3-dev python3-pip whois
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.30.2-1).
libffi-dev is already the newest version (3.3-6).
python3 is already the newest version (3.9.2-3).
python3-dev is already the newest version (3.9.2-3).
whois is already the newest version (5.5.10).
libssl-dev is already the newest version (1.1.1n-0+deb11u3+rpt1).
python3-pip is already the newest version (20.3.4-4+rpt1+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 33 not upgraded.
+ '[' n == y ']'
+ export MANAGE_NETWORK=false
+ MANAGE_NETWORK=false
+ '[' master = master ']'
++ curl -s https://raw.githubusercontent.com/Screenly/screenly-ose/master/requirements/requirements.host.txt
++ grep ansible
+ ANSIBLE_VERSION=ansible-core==2.12
+ sudo pip install ansible-core==2.12
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ansible-core==2.12
  Using cached https://www.piwheels.org/simple/ansible-core/ansible_core-2.12.0-py3-none-any.whl (2.1 MB)
Collecting jinja2
  Using cached https://www.piwheels.org/simple/jinja2/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting packaging
  Using cached https://www.piwheels.org/simple/packaging/packaging-21.3-py3-none-any.whl (40 kB)
Collecting resolvelib<0.6.0,>=0.5.3
  Using cached https://www.piwheels.org/simple/resolvelib/resolvelib-0.5.4-py2.py3-none-any.whl (12 kB)
Collecting PyYAML
  Using cached https://www.piwheels.org/simple/pyyaml/PyYAML-6.0-cp39-cp39-linux_armv6l.whl (45 kB)
Collecting cryptography
  Using cached cryptography-38.0.3.tar.gz (599 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cffi>=1.12
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.15.1-cp39-cp39-linux_armv6l.whl (364 kB)
Collecting pycparser
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
Collecting MarkupSafe>=2.0
  Using cached https://www.piwheels.org/simple/markupsafe/MarkupSafe-2.1.1-cp39-cp39-linux_armv6l.whl (23 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached https://www.piwheels.org/simple/pyparsing/pyparsing-3.0.9-py3-none-any.whl (98 kB)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpfjbfa6bb_in_process.py build_wheel /tmp/tmpdixpdyze
       cwd: /tmp/pip-install-qch2v40y/cryptography_56a86f9cbbe2418a8bb953f8cc2b7d8b
  Complete output (191 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv6l-cpython-39
  creating build/lib.linux-armv6l-cpython-39/cryptography
  copying src/cryptography/fernet.py -> build/lib.linux-armv6l-cpython-39/cryptography
  copying src/cryptography/exceptions.py -> build/lib.linux-armv6l-cpython-39/cryptography
  copying src/cryptography/__about__.py -> build/lib.linux-armv6l-cpython-39/cryptography
  copying src/cryptography/utils.py -> build/lib.linux-armv6l-cpython-39/cryptography
  copying src/cryptography/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat
  copying src/cryptography/hazmat/_oid.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat
  copying src/cryptography/hazmat/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat
  creating build/lib.linux-armv6l-cpython-39/cryptography/x509
  copying src/cryptography/x509/ocsp.py -> build/lib.linux-armv6l-cpython-39/cryptography/x509
  copying src/cryptography/x509/name.py -> build/lib.linux-armv6l-cpython-39/cryptography/x509
  copying src/cryptography/x509/oid.py -> build/lib.linux-armv6l-cpython-39/cryptography/x509
  copying src/cryptography/x509/general_name.py -> build/lib.linux-armv6l-cpython-39/cryptography/x509
  copying src/cryptography/x509/base.py -> build/lib.linux-armv6l-cpython-39/cryptography/x509
  copying src/cryptography/x509/extensions.py -> build/lib.linux-armv6l-cpython-39/cryptography/x509
  copying src/cryptography/x509/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/x509
  copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-armv6l-cpython-39/cryptography/x509
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/_asymmetric.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/_serialization.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/_cipheralgorithm.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends
  copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings
  copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/types.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/asymmetric
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/twofactor
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/ciphers
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/kdf
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/serialization
  copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/primitives/serialization
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/backends/openssl
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings/openssl
  running egg_info
  writing src/cryptography.egg-info/PKG-INFO
  writing dependency_links to src/cryptography.egg-info/dependency_links.txt
  writing requirements to src/cryptography.egg-info/requires.txt
  writing top-level names to src/cryptography.egg-info/top_level.txt
  reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/_build'
  warning: no previously-included files found matching 'vectors'
  warning: no previously-included files matching '*' found under directory 'vectors'
  warning: no previously-included files matching '*' found under directory '.github'
  warning: no previously-included files found matching 'release.py'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'dev-requirements.txt'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files found matching 'mypy.ini'
  warning: no previously-included files matching '*' found under directory '.circleci'
  adding license file 'LICENSE'
  adding license file 'LICENSE.APACHE'
  adding license file 'LICENSE.BSD'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
  /tmp/pip-build-env-145myq7g/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'cryptography.hazmat.bindings._rust' as data is deprecated, please list it in `packages`.
      !!
  
  
      ############################
      # Package would be ignored #
      ############################
      Python recognizes 'cryptography.hazmat.bindings._rust' as an importable package,
      but it is not listed in the `packages` configuration of setuptools.
  
      'cryptography.hazmat.bindings._rust' has been automatically added to the distribution only
      because it may contain data files, but this behavior is likely to change
      in future versions of setuptools (and therefore is considered deprecated).
  
      Please make sure that 'cryptography.hazmat.bindings._rust' is included as a package by using
      the `packages` configuration field or the proper discovery methods
      (for example by using `find_namespace_packages(...)`/`find_namespace:`
      instead of `find_packages(...)`/`find:`).
  
      You can read more about "package discovery" and "data files" on setuptools
      documentation page.
  
  
  !!
  
    check.warn(importable)
  copying src/cryptography/py.typed -> build/lib.linux-armv6l-cpython-39/cryptography
  copying src/cryptography/hazmat/bindings/_openssl.pyi -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings
  creating build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings/_rust
  copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-armv6l-cpython-39/cryptography/hazmat/bindings/_rust
  running build_ext
  running build_rust
  
      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation/ for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq/
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation/#rust
  
      Python: 3.9.2
      platform: Linux-5.15.61+-armv6l-with-glibc2.31
      pip: n/a
      setuptools: 65.5.1
      setuptools_rust: 1.5.2
      rustc: n/a
      =============================DEBUG ASSISTANCE=============================
  
  error: can't find Rust compiler
  
  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
  
  To update pip, run:
  
      pip install --upgrade pip
  
  and then retry package installation.
  
  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
  
  This package requires Rust >=1.48.0.
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
+ sudo -u pi ansible localhost -m git -a 'repo=https://github.com/screenly/screenly-ose.git dest=/home/pi/screenly version=master force=no'
sudo: ansible: command not found
+ cd /home/pi/screenly/ansible
/dev/fd/63: line 182: cd: /home/pi/screenly/ansible: No such file or directory
+ sudo -E ansible-playbook site.yml
sudo: ansible-playbook: command not found
+ /home/pi/screenly/bin/upgrade_containers.sh
/dev/fd/63: line 187: /home/pi/screenly/bin/upgrade_containers.sh: No such file or directory
+ sudo apt-get autoclean
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
+ sudo apt-get clean
+ sudo docker system prune -f
sudo: docker: command not found
+ sudo apt autoremove -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 33 not upgraded.
+ sudo apt-get install plymouth --reinstall -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 33 not upgraded.
Need to get 125 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian bullseye/main armhf plymouth armhf 0.9.5-3+rpt2 [125 kB]
Fetched 125 kB in 2s (69.1 kB/s)   
(Reading database ... 45565 files and directories currently installed.)
Preparing to unpack .../plymouth_0.9.5-3+rpt2_armhf.deb ...
Unpacking plymouth (0.9.5-3+rpt2) over (0.9.5-3+rpt2) ...
Setting up plymouth (0.9.5-3+rpt2) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for initramfs-tools (0.140) ...
+ sudo find /usr/share/doc -depth -type f '!' -name copyright -delete
+ sudo find /usr/share/doc -empty -delete
+ sudo rm -rf /usr/share/man /usr/share/groff '/usr/share/info/*' /usr/share/lintian /usr/share/linda /var/cache/man
+ sudo find /usr/share/locale -type f '!' -name en '!' -name 'de*' '!' -name 'es*' '!' -name 'ja*' '!' -name 'fr*' '!' -name 'zh*' -delete
+ sudo find /usr/share/locale -mindepth 1 -maxdepth 1 '!' -name 'en*' '!' -name 'de*' '!' -name 'es*' '!' -name 'ja*' '!' -name 'fr*' '!' -name 'zh*' '!' -name locale.alias -exec rm -r '{}' ';'
+ sudo chown -R pi:pi /home/pi
+ '[' '!' -f /etc/sudoers.d/010_pi-nopasswd ']'
+ check_defaultpw
+ '[' master = master ']'
+ '[' false = false ']'
+ set +x
Wrong salt length: 3 bytes when 8 <= n <= 16 expected.
The default raspberry pi password was not detected, continuing with installation...
++ git rev-parse --abbrev-ref HEAD
fatal: not a git repository (or any of the parent directories): .git
++ git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git
++ lsb_release -a
No LSB modules are available.
+ echo -e 'Screenly version: @\nDistributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye'
+ '[' false = false ']'
+ set +x
Installation completed.
You need to reboot the system for the installation to complete. Would you like to reboot now? (y/N)
```
</details>

**Comment by vpetersson** [comment] 2022-11-05 19:15
The error appears to be that the package cryptography fail to build, which in turn is likely due to lack of RAM in the Pi Zero. 

Not sure what the easiest fix for this, as this package is needed by ansible.

**Comment by AnchorHRG** [comment] 2022-11-05 20:10
@vpetersson Is there an older version of the install script that can be used for now for Pi Zero Ws, compatible with Buster? Or is there a pre built image based on Raspbian OS (Is [2022-11-04-raspberry-pi.zip](https://github.com/Screenly/screenly-ose/releases/download/v0.18.4/2022-11-04-raspberry-pi.zip) based on Raspbian OS?)? We need to install additional software alongside Screenly OSE.
Thanks for taking a look.

**Comment by vpetersson** [comment] 2022-11-05 20:12
Try the pre made image for pi 1. It's not based on raspbian but should in theory work.

**Comment by ScahR45** [comment] 2022-11-07 15:35
Hi
I've exactly the same error on Raspberry Pi 4 B 2GB with Raspbian Bulleyes lite 32bit

```
...
ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
```

Thank you for you work !

**Comment by vpetersson** [comment] 2022-11-07 15:36
> Hi I've exactly the same error on Raspberry Pi 4 B 2GB with Raspbian Bulleyes lite 32bit
> 
> ```
> ...
> ERROR: Failed building wheel for cryptography
> Failed to build cryptography
> ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
> ```
> 
> Thank you for you work !

That's odd. @nicomiguelino are you able to reproduce this?

**Comment by rebootit** [comment] 2022-11-07 15:52
Exactly the same thing on pi 2 and pi 3 when trying a fresh install

**Comment by vpetersson** [comment] 2022-11-07 15:54
So we're getting `error: can't find Rust compiler` in the logs. Not sure why this would have changed, since we have a pinned version of ansible. 

Can someone try just installing rust (`curl https://sh.rustup.rs -sSf | sh`) and then re-run the installer.

**Comment by nicomiguelino** [comment] 2022-11-07 19:00
Hi @rebootit & @vpetersson. Yes, I'm getting the same issue. I've ran the command for installing Rust (and I've sourced my `.bashrc` as well), but still getting the same error.

**Comment by vpetersson** [comment] 2022-11-08 08:21
This is odd though. I wonder what introduced this. It ran just fine a few weeks ago and I don't recall bumping up anything related to this.

**Comment by ScahR45** [comment] 2022-11-08 08:48
Hi,
I ran installation many times 2 weeks ago with success too
I just retrying this morning, even with rustc installed, cryptography installation always KO on 32bit raspbian bullseye
```
pi@raspberrypi:~ $ rustc -V
rustc 1.65.0 (897e37553 2022-11-02)
```

If i make a pip install cryptography, it block here (tested 2 times with fresh install) : 

```
pi@raspberrypi:~ $ pip install cryptography
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cryptography
  Downloading cryptography-38.0.3.tar.gz (599 kB)
     |████████████████████████████████| 599 kB 5.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cffi>=1.12
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.15.1-cp39-cp39-linux_armv7l.whl (364 kB)
Collecting pycparser
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (PEP 517) ... /

```

**Comment by vpetersson** [comment] 2022-11-08 09:02
I think i see what's going on here. Ansible might depend on a non-pinned version of cryptography and cryptography just released [a new version](https://pypi.org/project/cryptography/#history) (38.0.3) on November 1st. This release doesn't have any pre-compiled wheels yet. This is likely what broke things.

Assuming this is the case, the workaround is easy: just install cryptography first (`sudo pip install cryptography==38.0.2`) and then run the installer.  

Assuming that does the trick, we can easily port this to the installer.

**Comment by ScahR45** [comment] 2022-11-08 09:10
Yes  with cryptography 38.0.2 it works ! Thanks

**Comment by nicomiguelino** [comment] 2022-11-08 15:59
It works on my Pi 4 with 32-bit OS installed.

**Closed** 2022-11-08 16:39 UTC
