### ISSUE TITLE
Black Screen instead of Video

### ISSUE THREAD

**Issue by AntonyJayM** [Screenly/screenly-ose#1271] opened 2019-11-26 13:58 UTC
#### Overview of the Issue

When we upload a h.264 video to Screenly OSE we get a solid black screen. Other assets will play after however the video will not play. 

#### Reproduction Steps

Steps to reproduce this issue, eg:

* Upload a video and set it as live

### Environment

* Raspberry Pi Hardware Version: Model 3B Revision: 1.2 Ram: 1 GB Sony UK
* Screenly OSE Version: production@6c2c2fd

**Comment by vpetersson** [comment] 2019-11-26 14:32
Duplicate of #1261.

**Closed by vpetersson** 2019-11-26 14:32 UTC
