### ISSUE TITLE
crash : An unexpected TLS packet was received.

### ISSUE THREAD

**Issue by androidofon** [Screenly/screenly-ose#1040] opened 2019-03-01 14:25 UTC
Screenly OSE crashes and causes an error message on the web pages after a while.

Here is the error message:

Unable to load page
Problem occured while loading the URM
https://www ......
Error performing TLS handshake: An unexpected TLS packet was received.

This has been reproducible on a Raspberry PI 3 B +, as well as on a Raspberry 2, the problem is identical. Also tested on 2 different internet connections and recurring problem.
It is really binding and it forces to electrically disconnect the device for it to go again.

version of screenly ose: image_2018-11-23-Screenly-OSE-lite

The blocking pages were the screen time we app app itself or a web page itself.

See screenshot
![img_20190301_145818](https://user-images.githubusercontent.com/48128599/53644178-41b82b00-3c36-11e9-9c47-56e62fd04906.jpg)

Do you have a solution to the resolution of this bug?

**Comment by vpetersson** [comment] 2019-03-01 16:35
Duplicate of https://forums.screenly.io/t/crash-an-unexpected-tls-packet-was-received/36

**Closed** 2019-04-27 07:39 UTC
