### ISSUE TITLE
Blue Screenly Logo

### ISSUE THREAD

**Issue by eege** [Screenly/screenly-ose#802] opened 2018-04-19 19:23 UTC
Hi,

Blue background screenly logo comes in front of asset after successfully reverse ssh connection has been established.

SSH path
Screenly > SSH Server > SSH back to Screenly (reverse ssh)

Asset is a web page url contains white background and logo. 

![img_1330](https://user-images.githubusercontent.com/12582050/39013371-dc8d7e42-441f-11e8-82bb-c14e8279173b.JPG)

Screenly version is 2018-01-19-Screenly_OSE_4GB.img

P.S. Screenly logo does not appear in default weather and other 2 pages.

Thank you

Erhan

**Comment by antonmolodykh** [comment] 2018-04-23 14:53
Can you run `sudo journalctl > foobar.txt` and attach foobar.txt?

**Comment by antonmolodykh** [comment] 2018-06-22 09:15
I didn't find a reason in the logs, and also could not reproduce the problem myself.

**Comment by vpetersson** [comment] 2018-06-22 09:18
Also, @eege - please make sure to upgrade to the latest production version.

**Comment by vpetersson** [comment] 2018-07-24 07:33
Closing out ticket due to interactivity. Please comment if this is still the case.

**Comment by eege** [comment] 2018-08-01 19:56
issue still continues with latest version. To re-produce the problem, please update your /etc/rc.local with following line after "# Disable wifi power management" line

sleep 10
ifconfig wlan0 hw ether 36:31:62:c8:3b:9a

**Comment by vpetersson** [comment] 2018-08-02 10:47
@eege That's unfortunately not a viable solution upstream as what you are essential are doing is to change the MAC address of the wifi device.

**Comment by vpetersson** [comment] 2018-08-02 18:25
@eege This is kinda outside the scope of Screenly tbh. If there's a blocking process in `/etc/rc.local`, the entire boot process will stop. This is expected. You need to implement this using something more appropriate, such a `systemd` service.

**Closed by vpetersson** 2018-08-02 18:25 UTC
