### ISSUE TITLE
No Video Playback

### ISSUE THREAD

**Issue by mikekorncnx** [Screenly/screenly-ose#1627] opened 2022-10-05 01:47 UTC
Overview of the Issue
When we upload any video (MP4, MOV, YouTube link, etc) to Screenly OSE we get a solid black screen. Other assets (images) will play after however the video will not play.

Reproduction Steps

- Upload a video and set it as live

Environment

- Raspberry Pi Hardware Version: Pi 4 Model 4, 4GB RAM, 64 Bit

- Screenly OSE Version: qt5-5.15.2-buster-pi4

**Comment by vpetersson** [comment] 2022-10-05 07:53
Duplicate of #1590.

**Closed by vpetersson** 2022-10-05 07:53 UTC
