### ISSUE TITLE
Screenly OSE is freezing after working reliably for years

### ISSUE THREAD

**Issue by catsarecool999** [Screenly/screenly-ose#1012] opened 2019-01-08 15:27 UTC
#### Screenly OSE is freezing on random assets after 99.9% uptime for years

Here's the log from BalenaCloud --

08.01.19 10:22:46 (-0500)  main  Jan 08 15:22:46 f4b4026 python[236]: [2019-01-08 15:22:46 +0000] [277] [INFO] Booting worker with pid: 277
08.01.19 10:23:44 (-0500)  main  Jan 08 15:23:44 f4b4026 python[217]: Generating asset-list...
08.01.19 10:23:44 (-0500)  main  Jan 08 15:23:44 f4b4026 python[217]: Showing asset MUSIC TOGETHER BABIES (0-12 MONTHS).png (image)
08.01.19 10:23:44 (-0500)  main  Jan 08 15:23:44 f4b4026 python[217]: current url is file:///tmp/screenly_html/black_page.html
08.01.19 10:23:44 (-0500)  main  Jan 08 15:23:44 f4b4026 python[217]: Sleeping for 20
08.01.19 10:24:05 (-0500)  main  Jan 08 15:24:05 f4b4026 python[217]: Showing asset 4 Upcoming Events from LibCal (webpage)
08.01.19 10:24:05 (-0500)  main  Jan 08 15:24:05 f4b4026 python[217]: current url is https://www.URL HIDDEN FOR PRIVACY
08.01.19 10:24:05 (-0500)  main  Jan 08 15:24:05 f4b4026 python[217]: Sleeping for 30
08.01.19 10:24:35 (-0500)  main  Jan 08 15:24:35 f4b4026 python[217]: Showing asset MUSIC TOGETHER BABIES (0-12 MONTHS).png (image)
08.01.19 10:24:35 (-0500)  main  Jan 08 15:24:35 f4b4026 python[217]: current url is file:///tmp/screenly_html/black_page.html

The last time is where it gets stuck and just sits there forever.

I think it might be the web page...

**Comment by ealmonte32** [comment] 2019-01-08 20:32
@catsarecool999 like viktor says, without much data provided, there is little to go on for troubleshooting.. 
do you have a way to get the SD card out of the system and test using hard drive diagnostic tools?
do you want to upgrade the version of screenly and see if that helps?
does it always get stuck after the "music together babies.." image?

**Comment by trustees629** [comment] 2019-02-06 18:33
I, too, have been experiencing Screenly OSE freezing on this latest release (1ff5092). I tried to narrow it down to any certain thing but didn't have any luck. Most of the time it would freeze when clearing temporary cache. I have 2 Pi zero's running and I even went so far as to reformat the SD card on both and try again. I still had the issue. I ended up forcing it back to the production version (57dbde3) which has been working nonstop for 3 days. BTW, I'm using Balena cloud. I'm willing to help diagnose the issue on one of my systems if you're interested.

**Comment by rusko124** [comment] 2019-02-07 10:48
Hi everyone!
@trustees629  Could you provide more logs? How many assets and what types of assets are used? If this is a web pages would be great if you could provide the urls.

**Comment by trustees629** [comment] 2019-02-07 18:05
Sure. What logs would you like?

I have 21 assets and they are a mixture of JPG and PNG.

**Comment by ealmonte32** [comment] 2019-02-07 21:02
@trustees629 
While we wait for rusko to get back to you, can you paste into a text file and link, the outcome of command:
journalctl

But, there is a lot of messages that will come up, so in order to filter it to the day that the issue occurs, you could filter the logs for example say today you encountered the freezing, you can do:

journalctl | grep "Feb 07"

then copy data and i suggest attaching a text file with it..

**Comment by trustees629** [comment] 2019-02-09 15:18
A quick update... because I had reverted back to the production version, I took a different SD card and installed the latest. I added all the same assets and have left it running for 2 days now. Seems to be running fine so I'm at a loss. I'll keep an eye on it.

**Comment by ealmonte32** [comment] 2019-02-13 14:10
> A quick update... because I had reverted back to the production version, I took a different SD card and installed the latest. I added all the same assets and have left it running for 2 days now. Seems to be running fine so I'm at a loss. I'll keep an eye on it.

Although this is good news, now we cant troubleshoot =[ so we have no idea what was going on before..
I am one of those that likes to narrow down and isolate an issue so that it is documented and can be referenced you know.. oh well.

**Comment by vpetersson** [comment] 2019-02-21 17:27
Closing out this one due to inability to reproduce. Probably related to faulty SD card.

**Closed by vpetersson** 2019-02-21 17:27 UTC
